apiVersion: v1
kind: ConfigMap
metadata:
  name: ${PRODUCT_MS_NAME}-config
data:
  PORT: "${CONTAINER_RUNNING_PORT}"   
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_NAME: "${DB_NAME}"
  AUTH_SERVICE_URL: "${AUTH_SERVICE_URL}"
