apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: product-ms
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Container port
      nodePort: 30050 # Exposed port on minikube node (can be between 30000-32767)