apiVersion: v1
kind: Service
metadata:
  name: ${PRODUCT_MS_NAME}-service

spec:
  type: ClusterIP
  selector:
    app: ${PRODUCT_MS_NAME}
  ports:
    - protocol: TCP
      port: ${KUBERNETES_SERVICE_PORT}        # Service port
      targetPort: ${CONTAINER_RUNNING_PORT}  # Container port

#spec:
#  type: NodePort
#  selector:
#    app: ${PRODUCT_MS_NAME}
#  ports:
#    - protocol: TCP
#      port: ${KUBERNETES_SERVICE_PORT}        # Service port
#      targetPort: ${CONTAINER_RUNNING_PORT}  # Container port
#      nodePort: ${KUBERNETES_NODE_PORT} # Exposed port on minikube node (can be between 30000-32767)
