name: Build & Push Auth Service to ECR

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    name: Build & Push to Amazon ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .env file from example and secrets
        run: |
          cp .env.example .env.local
          sed -i 's|^JWT_SECRET=.*|JWT_SECRET=${{ secrets.JWT_SECRET }}|' .env.local
          sed -i 's|^DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|' .env.local
          sed -i 's|^DB_USER=.*|DB_USER=${{ secrets.DB_USER }}|' .env.local
          sed -i 's|^DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|' .env.local
          sed -i 's|^DB_NAME=.*|DB_NAME=${{ secrets.DB_NAME }}|' .env.local
          sed -i 's|^PORT=.*|PORT=${{ secrets.PORT }}|' .env.local
          sed -i 's|^DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|' .env.local
          sed -i 's|^AUTH_SERVICE_URL=.*|AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}|' .env.local

      - name: Configure AWS credentialss
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{secrets.CONTAINER_REPO_NAME}}:latest
